//module.exports.privateKey ='BbZJjyoXAdr8BUZuiKKARWimKfrSmQ6fv8kZ7OFfc';
//module.exports.password = '234789982fh234sjdfhaksdjfkasjdfkasjdfkasjdfkasjdhfkasjdfhka23423dsfhdrt34';
module.exports.mysqlrootpass='eeb73fd4'
module.exports.mysqlappcoddb='appcodedb'; //create database names, mysqlappcoddb an d
module.exports.mysqltelegramdb='heroku_1c71200bead0418'; //create database names, mysqlappcoddb an d
module.exports.mysqlappcoddbhost='localhost';
module.exports.mysqlappcoddbport='3306';
module.exports.mysqlappcoddbuser='bc1da87a9c48df';
//module.exports.mysqluser='root'
module.exports.mysqluser='bc1da87a9c48df';
//module.exports.serverIP='localhost';
module.exports.serverIP='us-cdbr-iron-east-01.cleardb.net';//live seevr if
module.exports.serverport=5001;
